# -*- coding: utf-8 -*-
"""ai_trading_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ILau22nH4Mxvut7ajRM-Y0X1DM1lbzXK
"""

import sys
import subprocess
import warnings
from datetime import timedelta

# --- 1. AYARLAR ---
warnings.filterwarnings("ignore")

def install(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])

try:
    import yfinance as yf
    import pandas as pd
    import numpy as np
    import plotly.graph_objects as go
    from plotly.subplots import make_subplots
    from sklearn.preprocessing import StandardScaler
    from sklearn.metrics import accuracy_score
    from tensorflow.keras.models import Sequential
    from tensorflow.keras.layers import Dense, LSTM, Dropout, Input, BatchNormalization
    from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
    from tensorflow.keras.optimizers import Adam
except ImportError:
    print("⚠️ Kütüphaneler eksik, kuruluyor...")
    libs = ["yfinance", "pandas", "numpy", "scikit-learn", "tensorflow", "plotly"]
    for lib in libs:
        install(lib)
    import yfinance as yf
    import pandas as pd
    import numpy as np
    import plotly.graph_objects as go
    from plotly.subplots import make_subplots
    from sklearn.preprocessing import StandardScaler
    from sklearn.metrics import accuracy_score
    from tensorflow.keras.models import Sequential
    from tensorflow.keras.layers import Dense, LSTM, Dropout, Input, BatchNormalization
    from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
    from tensorflow.keras.optimizers import Adam

# --- 2. GİRİŞ ---
def kullanici_girisi():
    print("\n" + "█"*70)
    print("   🔮 PRO TRADER AI - V15.0 (ORACLE MODE) 🔮   ")
    print("   >>> 30 GÜNLÜK VADE ANALİZİ | GÜNLÜK VERİLER (1D) <<<")
    print("█"*70)
    print("\nAnaliz Modu:")
    print("1. 🪙 Kripto")
    print("2. 🏢 Borsa")

    secim = input("\n👉 Seçim (1 veya 2): ").strip()

    if secim == "1":
        coin = input("🪙 Sembol (Örn: BTC, ETH, SOL): ").strip().upper()
        sembol = f"{coin}-USD" if not coin.endswith("-USD") else coin
        market_type = "CRYPTO"
    elif secim == "2":
        hisse = input("🏢 Sembol (Örn: THYAO.IS, TOASO.IS, AAPL): ").strip().upper()
        sembol = hisse
        market_type = "STOCK"
    else:
        sembol = "BTC-USD"
        market_type = "CRYPTO"

    return sembol, market_type

# --- 3. UZUN VADELİ VERİ HAZIRLIĞI ---
def veri_getir(symbol):
    print(f"📡 {symbol} için 10 yıllık günlük veriler çekiliyor...")
    try:
        # ÖNEMLİ DEĞİŞİKLİK: Saatlik yerine GÜNLÜK (1d) ve 10 Yıllık veri
        # Uzun vade tahmini için uzun geçmiş gerekir.
        df = yf.download(symbol, period="10y", interval="1d", progress=False)

        if df.empty:
            print("⚠️ 10 yıllık veri yok, maksimum veri çekiliyor...")
            df = yf.download(symbol, period="max", interval="1d", progress=False)

        if isinstance(df.columns, pd.MultiIndex):
            df.columns = [col[0] for col in df.columns]

        # Temizlik
        df.ffill(inplace=True)
        df.bfill(inplace=True)

        # --- UZUN VADE İNDİKATÖRLERİ ---

        # 1. Golden Cross Kontrolü (SMA 50 vs SMA 200)
        df['SMA_50'] = df['Close'].rolling(window=50).mean()
        df['SMA_200'] = df['Close'].rolling(window=200).mean()
        df['Trend_Ratio'] = df['SMA_50'] / df['SMA_200'] # 1'in üstündeyse boğa trendi

        # 2. RSI (Aylık trend için biraz daha yumuşak bakabiliriz ama standart 14 iyidir)
        delta = df['Close'].diff()
        gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
        loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
        rs = gain / loss
        df['RSI'] = 100 - (100 / (1 + rs))

        # 3. MACD
        exp12 = df['Close'].ewm(span=12, adjust=False).mean()
        exp26 = df['Close'].ewm(span=26, adjust=False).mean()
        df['MACD'] = exp12 - exp26

        # 4. Volatilite (ATR)
        high_low = df['High'] - df['Low']
        high_close = np.abs(df['High'] - df['Close'].shift())
        low_close = np.abs(df['Low'] - df['Close'].shift())
        ranges = pd.concat([high_low, high_close, low_close], axis=1)
        true_range = np.max(ranges, axis=1)
        df['ATR'] = true_range.rolling(14).mean()

        # 5. Log Return (Uzun vadeli birikimli getiri potansiyeli için)
        df['Log_Return'] = np.log(df['Close'] / df['Close'].shift(1))

        # --- HEDEF BELİRLEME (GELECEK 30 GÜN) ---
        # TARGET: 30 gün sonraki fiyat, bugünden yüksek mi?
        forecast_horizon = 30
        df['Target'] = (df['Close'].shift(-forecast_horizon) > df['Close']).astype(int)

        df.dropna(inplace=True)
        return df, forecast_horizon
    except Exception as e:
        print(f"Hata: {e}")
        sys.exit()

# --- 4. AI MOTORU (UZUN VADE) ---
def yapay_zeka_tahmin(df, horizon):
    print(f"🧠 AI: {horizon} Günlük Gelecek Trendi Öğreniliyor...")

    features = ['Log_Return', 'RSI', 'MACD', 'Trend_Ratio', 'ATR']

    split_idx = int(len(df) * 0.90)

    scaler = StandardScaler()
    data = np.zeros_like(df[features].values, dtype=float)
    data[:split_idx] = scaler.fit_transform(df[features].values[:split_idx])

    data[split_idx:] = scaler.transform(df[features].values[split_idx:])
    target = df['Target'].values

    # Geçmişe bakış: 60 gün (2 Ay) verisine bakıp, sonraki 1 ayı tahmin edecek.
    lookback = 60

    X, y = [], []
    # Son 'horizon' kadar veriyi eğitimde kullanamayız çünkü onların 30 gün sonrası yok.
    for i in range(lookback, len(data) - horizon): # Buradaki -horizon önemli!
        X.append(data[i-lookback:i])
        y.append(target[i]) # target zaten shift edilmişti

    X, y = np.array(X), np.array(y)

    n = len(X)
    fold_size = n // 4
    scores = []

    for fold in range(3):
        train_end = fold_size * (fold + 2)
        test_end = train_end + fold_size

        if test_end > n:
            break

        X_train = X[:train_end]
        y_train = y[:train_end]
        X_test = X[train_end:test_end]
        y_test = y[train_end:test_end]

        model = Sequential()
        model.add(Input(shape=(X_train.shape[1], X_train.shape[2])))
        model.add(LSTM(128, return_sequences=True))
        model.add(Dropout(0.4))
        model.add(BatchNormalization())
        model.add(LSTM(64, return_sequences=False))
        model.add(Dropout(0.4))
        model.add(Dense(32, activation='relu'))
        model.add(Dense(1, activation='sigmoid'))

        optimizer = Adam(learning_rate=0.0005)
        model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])

        es = EarlyStopping(monitor='val_accuracy', patience=20, restore_best_weights=True)
        lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=5, verbose=0)

        print(f"⏳ Fold {fold+1}/3 eğitiliyor...")
        model.fit(X_train, y_train, epochs=50, batch_size=32, verbose=0,
                  validation_data=(X_test, y_test), callbacks=[es, lr])

        y_pred_prob = model.predict(X_test, verbose=0)
        y_pred_class = (y_pred_prob > 0.5).astype(int)
        acc = accuracy_score(y_test, y_pred_class) * 100
        scores.append(acc)
        print(f"✅ Fold {fold+1} Accuracy: %{acc:.1f}")

    acc_score = np.mean(scores)
    last_seq = data[-lookback:].reshape(1, lookback, len(features))
    future_prob = model.predict(last_seq, verbose=0)[0][0]

    return future_prob, acc_score, horizon

# --- 5. GRAFİK (GELECEĞE BAKIŞ) ---
def grafik_ciz(df, symbol, prob, market_type, accuracy, horizon):
    print("🎨 Grafik: Gelecek projeksiyonu çiziliyor...")

    last_price = df['Close'].iloc[-1]
    last_date = df.index[-1]

    trend_yonu = "YÜKSELİŞ" if prob > 0.5 else "DÜŞÜŞ"
    guven_yuzdesi = prob * 100 if prob > 0.5 else (1 - prob) * 100
    renk = "#00F260" if prob > 0.5 else "#FF3333"

    # Gelecek Tarihi Hesapla
    future_date = last_date + timedelta(days=horizon)

    fig = make_subplots(
        rows=2, cols=1,
        shared_xaxes=True,
        vertical_spacing=0.08,
        row_heights=[0.70, 0.30],
        subplot_titles=(f"{symbol} UZUN VADE ANALİZİ ({horizon} Gün Sonrası)", "TREND GÜCÜ (SMA 50/200)")
    )

    # 1. Mumlar
    fig.add_trace(go.Candlestick(
        x=df.index, open=df['Open'], high=df['High'], low=df['Low'], close=df['Close'],
        name="Günlük Fiyat",
        increasing_line_color='#00F260', decreasing_line_color='#FF3333',
    ), row=1, col=1)

    # SMA Çizgileri
    fig.add_trace(go.Scatter(x=df.index, y=df['SMA_50'], line=dict(color='cyan', width=1), name="SMA 50"), row=1, col=1)
    fig.add_trace(go.Scatter(x=df.index, y=df['SMA_200'], line=dict(color='orange', width=1), name="SMA 200"), row=1, col=1)

    # --- GELECEK PROJEKSİYONU ---
    # Bugünden 30 gün sonrasına kesikli bir çizgi çekelim
    target_price_visual = last_price * (1.10 if prob > 0.5 else 0.90) # %10 temsili hareket

    fig.add_trace(go.Scatter(
        x=[last_date, future_date],
        y=[last_price, target_price_visual],
        mode='lines',
        line=dict(color=renk, width=2, dash='dot'),
        name=f"{horizon} Günlük Hedef Yönü"
    ), row=1, col=1)

    fig.add_trace(go.Scatter(
        x=[future_date], y=[target_price_visual],
        mode='markers+text',
        marker=dict(color=renk, size=25, symbol='star'),
        text=[f"{future_date.strftime('%d %b')}\n{trend_yonu}\n%{guven_yuzdesi:.1f}"],
        textposition="top center",
        textfont=dict(color=renk, size=14, family="Arial Black"),
        name="AI Hedef"
    ), row=1, col=1)

    # 2. Panel: RSI
    fig.add_trace(go.Scatter(x=df.index, y=df['RSI'], line=dict(color='white', width=1), name="RSI"), row=2, col=1)
    fig.add_hline(y=70, line_dash="dot", line_color="red", row=2, col=1)
    fig.add_hline(y=30, line_dash="dot", line_color="green", row=2, col=1)

    rangebreaks = []
    if market_type == "STOCK":
        rangebreaks.append(dict(bounds=["sat", "mon"]))

    # Zoom Ayarı: Son 1 Yıl + Gelecek 1 Ay
    zoom_start = df.index[-365]
    zoom_end = future_date + timedelta(days=5)

    fig.update_layout(
        title=dict(text=f"<b>{symbol}</b> | Fiyat: {last_price:.2f} | 30 Günlük Beklenti: <span style='color:{renk}'>{trend_yonu}</span>", font=dict(color="white", size=18)),
        template="plotly_dark",
        plot_bgcolor="#0b0e11", paper_bgcolor="#0b0e11",
        height=900,
        margin=dict(l=50, r=50, t=80, b=40),
        legend=dict(orientation="h", y=1, x=0.01, bgcolor="rgba(0,0,0,0.5)"),
        hovermode="x unified",
        xaxis=dict(
            rangebreaks=rangebreaks,
            rangeslider=dict(visible=False),
            showgrid=True, gridcolor="#1e222d",
            range=[zoom_start, zoom_end]
        ),
        yaxis=dict(side="right", gridcolor="#1e222d"),
        yaxis2=dict(range=[0, 100], showgrid=True, gridcolor="#1e222d", side="right"),
    )

    fig.show()

if __name__ == "__main__":
    s, m = kullanici_girisi()
    d, hor = veri_getir(s)
    prob, score, h = yapay_zeka_tahmin(d, hor)

    print(f"\n📊 Uzun Vade Analiz Sonucu:")
    print(f"📅 Bugün: {d.index[-1].strftime('%d-%m-%Y')} | Fiyat: {d['Close'].iloc[-1]:.2f}")
    if prob > 0.5:
        print(f"🚀 30 Gün Sonra ({h} Gün): YÜKSELİŞ Bekleniyor (İhtimal: %{prob*100:.1f})")
    else:
        print(f"🔻 30 Gün Sonra ({h} Gün): DÜŞÜŞ Bekleniyor (İhtimal: %{(1-prob)*100:.1f})")
    print(f"🏆 Geçmiş 30 Günlük Trendleri Bilme Başarısı: %{score:.1f}")

    grafik_ciz(d, s, prob, m, score, h)